### PR TITLE
Don't put >65535 strings in a heap (fixes #31)

### LINKED ISSUE #31: Inexact error
Hello,
I have found bug (probably overflow) when saving large array of strings.
The error can be replicated as 

> save("/dev/shm/test.jld2","df",fill("a",100000));

which returns
>ERROR: InexactError()
Stacktrace:
 [1] write_heap_object(::JLD2.JLDFile{JLD2.MmapIO}, ::Type{T} where T, ::Array{UInt8,1}, ::JLD2.JLDWriteSession{Dict{UInt64,JLD2.RelOffset}}) at /home/ubuntu/.julia/v0.6/JLD2/src/global_heaps.jl:70
 [2] store_vlen! at /home/ubuntu/.julia/v0.6/JLD2/src/data.jl:678 [inlined]
 [3] h5convert!(::JLD2.IndirectPointer, ::Type{JLD2.Vlen{String}}, ::JLD2.JLDFile{JLD2.MmapIO}, ::String, ::JLD2.JLDWriteSession{Dict{UInt64,JLD2.RelOffset}}) at /home/ubuntu/.julia/v0.6/JLD2/src/data.jl:753
 [4] write_data(::JLD2.MmapIO, ::JLD2.JLDFile{JLD2.MmapIO}, ::Array{String,1}, ::Type{JLD2.Vlen{String}}, ::JLD2.HasReferences, ::JLD2.JLDWriteSession{Dict{UInt64,JLD2.RelOffset}}) at /home/ubuntu/.julia/v0.6/JLD2/src/dataio.jl:178
 [5] write_dataset(::JLD2.JLDFile{JLD2.MmapIO}, ::JLD2.WriteDataspace{1,Tuple{}}, ::JLD2.VariableLengthDatatype{JLD2.FixedPointDatatype}, ::Type{JLD2.Vlen{String}}, ::Array{String,1}, ::JLD2.JLDWriteSession{Dict{UInt64,JLD2.RelOffset}}) at /home/ubuntu/.julia/v0.6/JLD2/src/datasets.jl:401
 [6] write(::JLD2.Group{JLD2.JLDFile{JLD2.MmapIO}}, ::String, ::Array{String,1}, ::JLD2.JLDWriteSession{Dict{UInt64,JLD2.RelOffset}}) at /home/ubuntu/.julia/v0.6/JLD2/src/groups.jl:119
 [7] (::JLD2.##38#39{String,Array{String,1},Tuple{}})(::JLD2.JLDFile{JLD2.MmapIO}) at /home/ubuntu/.julia/v0.6/JLD2/src/loadsave.jl:103
 [8] #jldopen#29(::Array{Any,1}, ::Function, ::JLD2.##38#39{String,Array{String,1},Tuple{}}, ::String, ::Vararg{String,N} where N) at /home/ubuntu/.julia/v0.6/JLD2/src/loadsave.jl:4
 [9] #save#37(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:JLD2}}, ::String, ::Array{String,1}) at /home/ubuntu/.julia/v0.6/JLD2/src/loadsave.jl:101
 [10] save(::FileIO.File{FileIO.DataFormat{:JLD2}}, ::String, ::Array{String,1}) at /home/ubuntu/.julia/v0.6/JLD2/src/loadsave.jl:98
 [11] #save#14(::Array{Any,1}, ::Function, ::String, ::String, ::Vararg{Any,N} where N) at /home/ubuntu/.julia/v0.6/FileIO/src/loadsave.jl:61
 [12] save(::String, ::String, ::Array{String,1}) at /home/ubuntu/.julia/v0.6/FileIO/src/loadsave.jl:61

Thanks for addressing this.

### PR DESCRIPTION
**Pull request by simonster**

### CODE REVIEW

File: test/rw.jl [hunk 1]
```diff
@@ -346,14 +349,7 @@ function checkexpr(a::Expr, b::Expr)
     @assert i >= length(a.args) && j >= length(b.args)
 end
 
-fn = joinpath(tempdir(),"test.jld")
-
-# Issue #106
```
Comment (tkelman) [inline test/rw.jl]: did you intend to delete this?

Comment (simonster) [inline test/rw.jl]: Yes. It was dead code and I don't think the original JLD issue should apply to the implementation of type lookup here.
