### PR TITLE
Fixes and updates for Julia 0.7

### LINKED ISSUE #74: package test not running in 0.7.0-alpha
In Windows 10, Julia 0.7.0-alpha, I was able to execute `Pkg.add("JLD2")`, but `Pkg.test("JLD2")` gave me the following error (after many deprecation warnings):

```
ERROR: LoadError: LoadError: syntax: local variable name "x" conflicts with an argument
Stacktrace:
 [1] include at .\boot.jl:314 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1071
 [3] include(::Module, ::String) at .\sysimg.jl:29
 [4] include(::String) at C:\Users\vavasis\.julia\packages\JLD2\6s4K\src\JLD2.jl:3
 [5] top-level scope
 [6] include at .\boot.jl:314 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1071
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] top-level scope
 [10] eval at .\boot.jl:316 [inlined]
 [11] eval(::Expr) at .\client.jl:394
 [12] macro expansion at .\none:3 [inlined]
 [13] top-level scope at .\<missing>:0
in expression starting at C:\Users\vavasis\.julia\packages\JLD2\6s4K\src\dataspaces.jl:47
in expression starting at C:\Users\vavasis\.julia\packages\JLD2\6s4K\src\JLD2.jl:426
```

### LINKED ISSUE #75: precompilation fails on 0.7 alpha
I used `add JLD2#master` on the most recent windows 10 0.7 alpha version.

Any ideas why it fails? (see the Error line below)
```
julia> using JLD2
[ Info: Precompiling module JLD2
WARNING: importing deprecated binding Base.Void into JLD2.
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:19
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:19
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:19
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:19
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:19
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:19
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:19
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:19
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:59
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:59
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:59
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:59
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:59
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:78
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:78
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:85
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:132
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:254
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:254
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\mmapio.jl:254
┌ Warning: `isbits(#= deprecated.jl:1678 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = define_packed(::DataType) at misc.jl:7
└ @ JLD2 misc.jl:7
┌ Warning: `unshift!` is deprecated, use `pushfirst!` instead.
│   caller = define_packed(::DataType) at misc.jl:10
└ @ JLD2 misc.jl:10
WARNING: importing deprecated binding Base.ObjectIdDict into JLD2.
WARNING: Base.ObjectIdDict is deprecated, use IdDict{Any, Any} instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\JLD2.jl:135
WARNING: Base.ObjectIdDict is deprecated, use IdDict{Any, Any} instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\JLD2.jl:135
┌ Warning: `isbits(#= deprecated.jl:1678 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = define_packed(::DataType) at misc.jl:7
└ @ JLD2 misc.jl:7
┌ Warning: `unshift!` is deprecated, use `pushfirst!` instead.
│   caller = define_packed(::DataType) at misc.jl:10
└ @ JLD2 misc.jl:10
┌ Warning: `isbits(#= deprecated.jl:1678 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = define_packed(::DataType) at misc.jl:7
└ @ JLD2 misc.jl:7
┌ Warning: `unshift!` is deprecated, use `pushfirst!` instead.
│   caller = define_packed(::DataType) at misc.jl:10
└ @ JLD2 misc.jl:10
┌ Warning: `isbits(#= deprecated.jl:1678 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = define_packed(::DataType) at misc.jl:7
└ @ JLD2 misc.jl:7
┌ Warning: `unshift!` is deprecated, use `pushfirst!` instead.
│   caller = define_packed(::DataType) at misc.jl:10
└ @ JLD2 misc.jl:10
┌ Warning: `isbits(#= deprecated.jl:1678 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = define_packed(::DataType) at misc.jl:7
└ @ JLD2 misc.jl:7
┌ Warning: `unshift!` is deprecated, use `pushfirst!` instead.
│   caller = define_packed(::DataType) at misc.jl:10
└ @ JLD2 misc.jl:10
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\dataspaces.jl:43
ERROR: LoadError: LoadError: syntax: local variable name "x" conflicts with an argument
Stacktrace:
 [1] include at .\boot.jl:314 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1071
 [3] include(::Module, ::String) at .\sysimg.jl:29
 [4] include(::String) at C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\JLD2.jl:3
 [5] top-level scope
 [6] include at .\boot.jl:314 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1071
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] top-level scope
 [10] eval at .\boot.jl:316 [inlined]
 [11] eval(::Expr) at .\client.jl:394
 [12] macro expansion at .\none:3 [inlined]
 [13] top-level scope at .\<missing>:0
in expression starting at C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\dataspaces.jl:47
in expression starting at C:\Users\bernhard.konig\.julia\packages\JLD2\PzLa\src\JLD2.jl:426
WARNING: Base.Void is deprecated, use Nothing instead.
 in module JLD2
WARNING: Base.Void is deprecated, use Nothing instead.
 in module JLD2
WARNING: Base.Void is deprecated, use Nothing instead.
 in module JLD2
WARNING: Base.Void is deprecated, use Nothing instead.
 in module JLD2
WARNING: Base.Void is deprecated, use Nothing instead.
 in module JLD2
WARNING: Base.Void is deprecated, use Nothing instead.
 in module JLD2
WARNING: Base.Void is deprecated, use Nothing instead.
 in module JLD2
WARNING: Base.Void is deprecated, use Nothing instead.
 in module JLD2
ERROR: Failed to precompile JLD2 to C:\Users\bernhard.konig\.julia\compiled\v0.7\JLD2\O1Ey.ji.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at .\loading.jl:1207
 [3] _require(::Base.PkgId) at .\loading.jl:1007
 [4] require(::Base.PkgId) at .\loading.jl:878
 [5] require(::Module, ::Symbol) at .\loading.jl:873

julia>
```

### PR DESCRIPTION
**Pull request by ararslan**
Changes from #76 are included here with authorship preserved.

Fixes #75
Fixes #74
Closes #76

### CODE REVIEW

**Comment by ararslan** [comment]
0.7 is hitting this:
```
ERROR: LoadError: LoadError: For emptytype, read value EmptyType() does not agree with written value EmptyType()
Stacktrace:
 [1] error(::String, ::String, ::String) at ./error.jl:42
 [2] macro expansion at /home/travis/build/simonster/JLD2.jl/test/rw.jl:323 [inlined]
 [3] macro expansion at util.jl:156 [inlined]
 [4] top-level scope at /home/travis/build/simonster/JLD2.jl/test/rw.jl:472
 [5] include at ./boot.jl:314 [inlined]
 [6] include_relative(::Module, ::String) at ./loading.jl:1071
 [7] include(::Module, ::String) at ./sysimg.jl:29
 [8] include(::String) at ./client.jl:393
 [9] top-level scope
 [10] include at ./boot.jl:314 [inlined]
 [11] include_relative(::Module, ::String) at ./loading.jl:1071
 [12] include(::Module, ::String) at ./sysimg.jl:29
 [13] include(::String) at ./client.jl:393
 [14] top-level scope
in expression starting at /home/travis/build/simonster/JLD2.jl/test/rw.jl:323
in expression starting at /home/travis/build/simonster/JLD2.jl/test/runtests.jl:6
```
It sure seems like `EmptyType()` and `EmptyType()` agree... Maybe a macro hygiene issue in `@check`?

**Comment by simonster** [comment]
I think it just needs an `iseq` method. It used to be the case that:

```
julia> mutable struct X end; isequal(X(), X())
true
```

but it seems this no longer holds.

**Comment by ararslan** [comment]
Good catch, Simon! I've added some methods that seem like they should be sufficient, but I'm still getting
```
ERROR: LoadError: LoadError: For emptyit, read value EmptyIT(EmptyType()) does not
agree with written value EmptyIT(EmptyType())
```

**Comment by ararslan** [comment]
Whoops, too visually similar, missed that `IT` wasn't in the `Union` already. Thanks!

**Comment by ararslan** [comment]
Alright, tests pass locally on 0.7 now, so hopefully CI agrees. Thanks for the help, Simon! I've kept the commits logically separate but you can squash merge (at your leisure) if you'd prefer.

**Comment by 00vareladavid** [comment]
While `isa(x, Nothing)` is being changed, wouldn't it be more idiomatic to say `x === nothing`? Since `Nothing` is a singleton type?

**Comment by ararslan** [comment]
Yeah I suppose so, but I don't plan on making any more changes in this PR unless absolutely necessary. There are more deprecations to be fixed later anyway, and we can always do a stylistic pass at some point as well.

File: test/runtests.jl [hunk 1]
```diff
@@ -8,5 +8,10 @@ include("append.jl")
 include("groups.jl")
 include("consistency.jl")
 include("loadsave.jl")
-include("recon.jl")
+
+# Only run the reconstruction tests on versions where `workspace` is a thing
+if VERSION < v"0.7.0-DEV.2917"
+    include("recon.jl")
```
Comment (simonster) [inline test/runtests.jl]: At some point we should run these on 0.7. The right approach is probably either to come up with some trickery involving replacing the module that contains the type so that they'll have to be reconstructed, or run the code to write the types in a separate process. But this can wait for another PR.

**Comment by simonster** [comment]
Thanks!
